//
// Created by Matt Whitaker on 04/03/2021.
//

#ifndef KAISHIENGINE_INCLUDE_PLATFORM_API_OPENGL_OPENGL4_H_
#define KAISHIENGINE_INCLUDE_PLATFORM_API_OPENGL_OPENGL4_H_

#endif  // KAISHIENGINE_INCLUDE_PLATFORM_API_OPENGL_OPENGL4_H_
