//
// Created by Matt Whitaker on 17/04/2021.
//

#ifndef KAISHIENGINE_INCLUDE_PLATFORM_API_OPENGLES_OPENGLES2_H_
#define KAISHIENGINE_INCLUDE_PLATFORM_API_OPENGLES_OPENGLES2_H_

namespace Kaishi {}  // namespace Kaishi

#endif //KAISHIENGINE_INCLUDE_PLATFORM_API_OPENGLES_OPENGLES2_H_
